# Numpy :

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

The core functionality of NumPy is its "ndarray", for n-dimensional array, data structure. These arrays are strided views on memory. In contrast to Python's built-in list data structure, these arrays are homogeneously typed: all elements of a single array must be of the same type.

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]

In [3]:
arr= np.array(lst)

In [4]:
arr

array([1, 2, 3, 4, 5])

In [7]:
arr[1:]

array([2, 3, 4, 5])

In [8]:
lst1 = [2,3,4,5,6,3]
lst2 = [3,5,7,8,9,5]
lst3 = [2,5,4,3,7,8]

In [10]:
arr1 = np.array([lst1,lst2,lst3])

In [11]:
arr1

array([[2, 3, 4, 5, 6, 3],
       [3, 5, 7, 8, 9, 5],
       [2, 5, 4, 3, 7, 8]])

In [12]:
arr1.shape

(3, 6)

In [53]:
arr1[1:,3:5]

array([[8, 9],
       [3, 7]])

In [54]:
arr1[1:2,1:5]

array([[5, 7, 8, 9]])

In [13]:
arr2= arr1.reshape(9,2)

In [14]:
arr2

array([[2, 3],
       [4, 5],
       [6, 3],
       [3, 5],
       [7, 8],
       [9, 5],
       [2, 5],
       [4, 3],
       [7, 8]])

In [15]:
arr

array([1, 2, 3, 4, 5])

In [17]:
arr
arr3= arr.copy()
arr3*2

array([ 2,  4,  6,  8, 10])

In [18]:
arr

array([1, 2, 3, 4, 5])

In [22]:
arr4= np.arange(0,10).reshape(2,5)

In [23]:
arr4

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
# random.rand genrates random values between 0-1 for given size
arr5 = np.random.rand(3,3)
arr5

array([[0.5810179 , 0.51799066, 0.33253773],
       [0.98698241, 0.44536842, 0.29920265],
       [0.24339988, 0.67362983, 0.92239826]])

In [28]:
# random.randn generates statndard normal values
arr6 = np.random.randn(4,4)
arr6

array([[ 1.81971766, -0.58515631,  0.54337134,  0.97158552],
       [-0.71165072,  0.06458551, -0.76434234,  0.01990719],
       [-2.05583345,  0.21001336,  1.32300253, -1.87033299],
       [ 0.31316044,  0.69761264,  0.0583155 , -0.7152678 ]])

In [36]:
arr7= np.random.randint(5,100,20).reshape(4,5)
arr7

array([[80, 60, 61, 48, 21],
       [10, 16, 15, 59, 87],
       [73, 62, 18, 15,  8],
       [34, 52, 56,  9, 42]])

In [43]:
arr8= np.ones(6, dtype=int).reshape(2,3)
arr8

array([[1, 1, 1],
       [1, 1, 1]])

In [49]:
arr9 = np.random.random_sample(5)
arr9

array([0.78221862, 0.08468431, 0.77335824, 0.67358587, 0.41188011])